<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H7UugW7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h7UugW7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'validationService' => ['privates', 'App\\Service\\InputValidationService', 'getInputValidationServiceService', true],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'entityManager' => '?',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
            'validationService' => 'App\\Service\\InputValidationService',
        ]);

        if (isset($container->privates['.service_locator.h7UugW7'])) {
            return $container->privates['.service_locator.h7UugW7'];
        }

        return $container->privates['.service_locator.h7UugW7'] = $instance;
    }
}
