<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RYHLj_RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rYHLj.R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.rYHLj.R'])) {
            return $container->privates['.service_locator.rYHLj.R'];
        }

        return $container->privates['.service_locator.rYHLj.R'] = $instance;
    }
}
