<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Asz5hGVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Asz5hGV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'livraisonRepository' => ['privates', 'App\\Repository\\LivraisonRepository', 'getLivraisonRepositoryService', true],
            'profanityFilter' => ['privates', 'App\\Service\\ProfanityFilterService', 'getProfanityFilterServiceService', true],
            'validationService' => ['privates', 'App\\Service\\InputValidationService', 'getInputValidationServiceService', true],
        ], [
            'entityManager' => '?',
            'livraisonRepository' => 'App\\Repository\\LivraisonRepository',
            'profanityFilter' => 'App\\Service\\ProfanityFilterService',
            'validationService' => 'App\\Service\\InputValidationService',
        ]);

        if (isset($container->privates['.service_locator.Asz5hGV'])) {
            return $container->privates['.service_locator.Asz5hGV'];
        }

        return $container->privates['.service_locator.Asz5hGV'] = $instance;
    }
}
