<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XS00oa2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XS00oa2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'productCatalogAiService' => ['privates', 'App\\Service\\ProductCatalogAiService', 'getProductCatalogAiServiceService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'entityManager' => '?',
            'productCatalogAiService' => 'App\\Service\\ProductCatalogAiService',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);

        if (isset($container->privates['.service_locator.XS00oa2'])) {
            return $container->privates['.service_locator.XS00oa2'];
        }

        return $container->privates['.service_locator.XS00oa2'] = $instance;
    }
}
