<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FWavo4ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FWavo4Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FWavo4Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedbackInsightService' => ['privates', 'App\\Service\\FeedbackInsightService', 'getFeedbackInsightServiceService', true],
            'feedbackRepository' => ['privates', 'App\\Repository\\FeedbackRepository', 'getFeedbackRepositoryService', true],
            'ligneCommandeRepository' => ['privates', 'App\\Repository\\LigneCommandeRepository', 'getLigneCommandeRepositoryService', true],
            'sentimentAnalyzer' => ['privates', 'App\\Service\\AISentimentService', 'getAISentimentServiceService', true],
        ], [
            'feedbackInsightService' => 'App\\Service\\FeedbackInsightService',
            'feedbackRepository' => 'App\\Repository\\FeedbackRepository',
            'ligneCommandeRepository' => 'App\\Repository\\LigneCommandeRepository',
            'sentimentAnalyzer' => 'App\\Service\\AISentimentService',
        ]);
    }
}
