<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KhQBAUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.khQ_BAU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reponseRepository' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
        ], [
            'entityManager' => '?',
            'reponseRepository' => 'App\\Repository\\ReponseRepository',
        ]);

        if (isset($container->privates['.service_locator.khQ_BAU'])) {
            return $container->privates['.service_locator.khQ_BAU'];
        }

        return $container->privates['.service_locator.khQ_BAU'] = $instance;
    }
}
