<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VAn7ydCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vAn7ydC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'inputValidationService' => ['privates', 'App\\Service\\InputValidationService', 'getInputValidationServiceService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'profilePhotoService' => ['privates', 'App\\Service\\ProfilePhotoService', 'getProfilePhotoServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'inputValidationService' => 'App\\Service\\InputValidationService',
            'passwordHasher' => '?',
            'profilePhotoService' => 'App\\Service\\ProfilePhotoService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.vAn7ydC'])) {
            return $container->privates['.service_locator.vAn7ydC'];
        }

        return $container->privates['.service_locator.vAn7ydC'] = $instance;
    }
}
