<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FigcACJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.figcACJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.figcACJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'currencyConversionService' => ['privates', 'App\\Service\\CurrencyConversionService', 'getCurrencyConversionServiceService', true],
            'feedbackRepository' => ['privates', 'App\\Repository\\FeedbackRepository', 'getFeedbackRepositoryService', true],
            'ligneCommandeRepository' => ['privates', 'App\\Repository\\LigneCommandeRepository', 'getLigneCommandeRepositoryService', true],
            'productCatalogAiService' => ['privates', 'App\\Service\\ProductCatalogAiService', 'getProductCatalogAiServiceService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'currencyConversionService' => 'App\\Service\\CurrencyConversionService',
            'feedbackRepository' => 'App\\Repository\\FeedbackRepository',
            'ligneCommandeRepository' => 'App\\Repository\\LigneCommandeRepository',
            'productCatalogAiService' => 'App\\Service\\ProductCatalogAiService',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
