<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GYUZx5pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gYUZx5p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gYUZx5p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'feedbackInsightService' => ['privates', 'App\\Service\\FeedbackInsightService', 'getFeedbackInsightServiceService', true],
            'feedbackRepository' => ['privates', 'App\\Repository\\FeedbackRepository', 'getFeedbackRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'sentimentAnalyzer' => ['privates', 'App\\Service\\AISentimentService', 'getAISentimentServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'feedbackInsightService' => 'App\\Service\\FeedbackInsightService',
            'feedbackRepository' => 'App\\Repository\\FeedbackRepository',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
            'sentimentAnalyzer' => 'App\\Service\\AISentimentService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
