<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MqrAVoWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MqrAVoW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MqrAVoW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productQrCodeService' => ['privates', 'App\\Service\\ProductQrCodeService', 'getProductQrCodeServiceService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'productQrCodeService' => 'App\\Service\\ProductQrCodeService',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
