<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DkjT523Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DkjT523' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ligneCommandeRepository' => ['privates', 'App\\Repository\\LigneCommandeRepository', 'getLigneCommandeRepositoryService', true],
        ], [
            'entityManager' => '?',
            'ligneCommandeRepository' => 'App\\Repository\\LigneCommandeRepository',
        ]);

        if (isset($container->privates['.service_locator.DkjT523'])) {
            return $container->privates['.service_locator.DkjT523'];
        }

        return $container->privates['.service_locator.DkjT523'] = $instance;
    }
}
