<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAISentimentServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AISentimentService' shared autowired service.
     *
     * @return \App\Service\AISentimentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AISentimentService.php';

        return $container->privates['App\\Service\\AISentimentService'] = new \App\Service\AISentimentService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('HUGGINGFACE_API_KEY'));
    }
}
