<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilePhotoServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ProfilePhotoService' shared autowired service.
     *
     * @return \App\Service\ProfilePhotoService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProfilePhotoService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'InputValidationService.php';

        return $container->privates['App\\Service\\ProfilePhotoService'] = new \App\Service\ProfilePhotoService(\dirname(__DIR__, 4), ($container->privates['App\\Service\\InputValidationService'] ??= new \App\Service\InputValidationService()), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('HUGGINGFACE_API_KEY'));
    }
}
