<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfanityFilterServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ProfanityFilterService' shared autowired service.
     *
     * @return \App\Service\ProfanityFilterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProfanityFilterService.php';

        return $container->privates['App\\Service\\ProfanityFilterService'] = new \App\Service\ProfanityFilterService();
    }
}
