<?php

namespace ContainerXfmafll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordResetServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PasswordResetService' shared autowired service.
     *
     * @return \App\Service\PasswordResetService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PasswordResetService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Service\\PasswordResetService'])) {
            return $container->privates['App\\Service\\PasswordResetService'];
        }
        $b = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\Service\\PasswordResetService'])) {
            return $container->privates['App\\Service\\PasswordResetService'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Service\\PasswordResetService'])) {
            return $container->privates['App\\Service\\PasswordResetService'];
        }

        $instance = new \App\Service\PasswordResetService(new \Symfony\Component\Mailer\Mailer($a, $b, $c), $container->getEnv('APP_SECRET'), $container->getEnv('MAILER_DSN'), $container->getEnv('MAILER_FROM_ADDRESS'), $container->getEnv('TWILIO_ACCOUNT_SID'), $container->getEnv('TWILIO_AUTH_TOKEN'), $container->getEnv('TWILIO_FROM_NUMBER'));

        if (isset($container->privates['App\\Service\\PasswordResetService'])) {
            return $container->privates['App\\Service\\PasswordResetService'];
        }

        return $container->privates['App\\Service\\PasswordResetService'] = $instance;
    }
}
