parameters:
  hugging_face_api_key: "%env(HUGGINGFACE_API_KEY)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $httpClient: "@http_client"
      $projectDir: "%kernel.project_dir%"
      $appSecret: "%env(APP_SECRET)%"
      $appEnv: "%kernel.environment%"
      $mailerDsn: "%env(MAILER_DSN)%"
      $mailerFromAddress: "%env(MAILER_FROM_ADDRESS)%"
      $twilioAccountSid: "%env(TWILIO_ACCOUNT_SID)%"
      $twilioAuthToken: "%env(TWILIO_AUTH_TOKEN)%"
      $twilioFromNumber: "%env(TWILIO_FROM_NUMBER)%"
      $huggingfaceApiKey: "%env(HUGGINGFACE_API_KEY)%"
      $huggingFaceApiKey: "%env(HUGGINGFACE_API_KEY)%"

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
